theme = "fleet_dark"

[keys.normal]
"C-r" = [":config-reload"]
"C-s" = [":w"]
"C-o" = [":open ~/.config/helix/config.toml"]
"g" = { a = "code_action" }
"G" = ["goto_last_line"]
"Z" = { Q = ":quit!" ,  Z = ":write-quit!" }
"D" = ["extend_to_line_bounds", "delete_selection"]
"0" = ["goto_line_start"]
"$" = ["goto_line_end"]
"=" = [ ":format" ]

[keys.select]
"D" = ["extend_to_line_bounds", "delete_selection"]